apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
spec:
  type: LoadBalancer   # I am using this mode because of EKS
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
