apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          env:
            - name: ENVIRONMENT
              value: production
  strategy:
    canary:
      steps:
        - setWeight: 50        
        - pause: {duration: 15s}
        - setWeight: 100       
      trafficRouting:
