apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          env:
            - name: ENVIRONMENT
              value: production
          ports:
            - containerPort: 80
  strategy:
    blueGreen:
      activeService: nginx-service
      previewService: nginx-preview
      autoPromotionEnabled: true
