apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverkey-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: ENVIRONMENT
              value: production
        - name: dependency-track
          env:
            - name: ENVIRONMENT
              value: production
