apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverkey-deployment
  namespace: default
  labels:
    app: silverkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silverkey
  template:
    metadata:
      labels:
        app: silverkey
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: frontend
          image: 645537741587.dkr.ecr.us-east-1.amazonaws.com/joe/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
        - name: dependency-track
          image: 645537741587.dkr.ecr.us-east-1.amazonaws.com/joe/backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi"
