apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverkey-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: ENVIRONMENT
              value: dev
        - name: dependency-track
          env:
            - name: ENVIRONMENT
              value: dev
